# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: kessel/inventory/v1beta1/authz/check.proto for package 'kessel.inventory.v1beta1.authz'

require 'grpc'
require 'kessel/inventory/v1beta1/authz/check_pb'

module Kessel
  module Inventory
    module V1beta1
      module Authz
        module KesselCheckService
          class Service

            include ::GRPC::GenericService

            self.marshal_class_method = :encode
            self.unmarshal_class_method = :decode
            self.service_name = 'kessel.inventory.v1beta1.authz.KesselCheckService'

            # Checks for the existence of a single Relationship 
            # (a Relation between a Resource and a Subject or Subject Set).
            rpc :Check, ::Kessel::Inventory::V1beta1::Authz::CheckRequest, ::Kessel::Inventory::V1beta1::Authz::CheckResponse
            rpc :CheckForUpdate, ::Kessel::Inventory::V1beta1::Authz::CheckForUpdateRequest, ::Kessel::Inventory::V1beta1::Authz::CheckForUpdateResponse
          end

          Stub = Service.rpc_stub_class
        end
      end
    end
  end
end
