# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kessel/inventory/v1beta1/authz/common.proto

require 'google/protobuf'

require 'buf/validate/validate_pb'


descriptor_data = "\n+kessel/inventory/v1beta1/authz/common.proto\x12\x1ekessel.inventory.v1beta1.authz\x1a\x1b\x62uf/validate/validate.proto\"\xdc\x01\n\x0cRelationship\x12S\n\x08resource\x18\x01 \x01(\x0b\x32/.kessel.inventory.v1beta1.authz.ObjectReferenceB\x06\xbaH\x03\xc8\x01\x01R\x08resource\x12#\n\x08relation\x18\x02 \x01(\tB\x07\xbaH\x04r\x02\x10\x01R\x08relation\x12R\n\x07subject\x18\x03 \x01(\x0b\x32\x30.kessel.inventory.v1beta1.authz.SubjectReferenceB\x06\xbaH\x03\xc8\x01\x01R\x07subject\"\x93\x01\n\x10SubjectReference\x12\x1f\n\x08relation\x18\x01 \x01(\tH\x00R\x08relation\x88\x01\x01\x12Q\n\x07subject\x18\x02 \x01(\x0b\x32/.kessel.inventory.v1beta1.authz.ObjectReferenceB\x06\xbaH\x03\xc8\x01\x01R\x07subjectB\x0b\n\t_relation\"}\n\x11RequestPagination\x12\x1d\n\x05limit\x18\x01 \x01(\rB\x07\xbaH\x04*\x02 \x00R\x05limit\x12\x32\n\x12\x63ontinuation_token\x18\x02 \x01(\tH\x00R\x11\x63ontinuationToken\x88\x01\x01\x42\x15\n\x13_continuation_token\"C\n\x12ResponsePagination\x12-\n\x12\x63ontinuation_token\x18\x01 \x01(\tR\x11\x63ontinuationToken\"r\n\x0fObjectReference\x12\x46\n\x04type\x18\x01 \x01(\x0b\x32*.kessel.inventory.v1beta1.authz.ObjectTypeB\x06\xbaH\x03\xc8\x01\x01R\x04type\x12\x17\n\x02id\x18\x02 \x01(\tB\x07\xbaH\x04r\x02\x10\x01R\x02id\"P\n\nObjectType\x12%\n\tnamespace\x18\x01 \x01(\tB\x07\xbaH\x04r\x02\x10\x01R\tnamespace\x12\x1b\n\x04name\x18\x02 \x01(\tB\x07\xbaH\x04r\x02\x10\x01R\x04name\"\xb8\x01\n\x0b\x43onsistency\x12\x34\n\x10minimize_latency\x18\x01 \x01(\x08\x42\x07\xbaH\x04j\x02\x08\x01H\x00R\x0fminimizeLatency\x12]\n\x11\x61t_least_as_fresh\x18\x02 \x01(\x0b\x32\x30.kessel.inventory.v1beta1.authz.ConsistencyTokenH\x00R\x0e\x61tLeastAsFreshB\x14\n\x0brequirement\x12\x05\xbaH\x02\x08\x01\"1\n\x10\x43onsistencyToken\x12\x1d\n\x05token\x18\x01 \x01(\tB\x07\xbaH\x04r\x02\x10\x01R\x05tokenB~\n.org.project_kessel.api.inventory.v1beta1.authzP\x01ZJgithub.com/project-kessel/inventory-api/api/kessel/inventory/v1beta1/authzb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Kessel
  module Inventory
    module V1beta1
      module Authz
        Relationship = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kessel.inventory.v1beta1.authz.Relationship").msgclass
        SubjectReference = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kessel.inventory.v1beta1.authz.SubjectReference").msgclass
        RequestPagination = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kessel.inventory.v1beta1.authz.RequestPagination").msgclass
        ResponsePagination = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kessel.inventory.v1beta1.authz.ResponsePagination").msgclass
        ObjectReference = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kessel.inventory.v1beta1.authz.ObjectReference").msgclass
        ObjectType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kessel.inventory.v1beta1.authz.ObjectType").msgclass
        Consistency = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kessel.inventory.v1beta1.authz.Consistency").msgclass
        ConsistencyToken = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kessel.inventory.v1beta1.authz.ConsistencyToken").msgclass
      end
    end
  end
end
