# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kessel/inventory/v1beta2/allowed.proto

require 'google/protobuf'


descriptor_data = "\n&kessel/inventory/v1beta2/allowed.proto\x12\x18kessel.inventory.v1beta2*G\n\x07\x41llowed\x12\x17\n\x13\x41LLOWED_UNSPECIFIED\x10\x00\x12\x10\n\x0c\x41LLOWED_TRUE\x10\x01\x12\x11\n\rALLOWED_FALSE\x10\x02\x42r\n(org.project_kessel.api.inventory.v1beta2P\x01ZDgithub.com/project-kessel/inventory-api/api/kessel/inventory/v1beta2b\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Kessel
  module Inventory
    module V1beta2
      Allowed = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kessel.inventory.v1beta2.Allowed").enummodule
    end
  end
end
