# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kessel/inventory/v1beta2/check_self_response.proto

require 'google/protobuf'

require 'kessel/inventory/v1beta2/allowed_pb'
require 'kessel/inventory/v1beta2/consistency_token_pb'


descriptor_data = "\n2kessel/inventory/v1beta2/check_self_response.proto\x12\x18kessel.inventory.v1beta2\x1a&kessel/inventory/v1beta2/allowed.proto\x1a\x30kessel/inventory/v1beta2/consistency_token.proto\"\xa9\x01\n\x11\x43heckSelfResponse\x12;\n\x07\x61llowed\x18\x01 \x01(\x0e\x32!.kessel.inventory.v1beta2.AllowedR\x07\x61llowed\x12W\n\x11\x63onsistency_token\x18\x02 \x01(\x0b\x32*.kessel.inventory.v1beta2.ConsistencyTokenR\x10\x63onsistencyTokenBr\n(org.project_kessel.api.inventory.v1beta2P\x01ZDgithub.com/project-kessel/inventory-api/api/kessel/inventory/v1beta2b\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Kessel
  module Inventory
    module V1beta2
      CheckSelfResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kessel.inventory.v1beta2.CheckSelfResponse").msgclass
    end
  end
end
