# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kessel/inventory/v1beta2/check_self_bulk_response.proto

require 'google/protobuf'

require 'kessel/inventory/v1beta2/check_self_bulk_request_pb'
require 'kessel/inventory/v1beta2/allowed_pb'
require 'buf/validate/validate_pb'
require 'google/rpc/status_pb'
require 'kessel/inventory/v1beta2/consistency_token_pb'


descriptor_data = "\n7kessel/inventory/v1beta2/check_self_bulk_response.proto\x12\x18kessel.inventory.v1beta2\x1a\x36kessel/inventory/v1beta2/check_self_bulk_request.proto\x1a&kessel/inventory/v1beta2/allowed.proto\x1a\x1b\x62uf/validate/validate.proto\x1a\x17google/rpc/status.proto\x1a\x30kessel/inventory/v1beta2/consistency_token.proto\"X\n\x19\x43heckSelfBulkResponseItem\x12;\n\x07\x61llowed\x18\x01 \x01(\x0e\x32!.kessel.inventory.v1beta2.AllowedR\x07\x61llowed\"\xec\x01\n\x19\x43heckSelfBulkResponsePair\x12L\n\x07request\x18\x01 \x01(\x0b\x32\x32.kessel.inventory.v1beta2.CheckSelfBulkRequestItemR\x07request\x12I\n\x04item\x18\x02 \x01(\x0b\x32\x33.kessel.inventory.v1beta2.CheckSelfBulkResponseItemH\x00R\x04item\x12*\n\x05\x65rror\x18\x03 \x01(\x0b\x32\x12.google.rpc.StatusH\x00R\x05\x65rrorB\n\n\x08response\"\xc5\x01\n\x15\x43heckSelfBulkResponse\x12S\n\x05pairs\x18\x01 \x03(\x0b\x32\x33.kessel.inventory.v1beta2.CheckSelfBulkResponsePairB\x08\xbaH\x05\x92\x01\x02\x08\x01R\x05pairs\x12W\n\x11\x63onsistency_token\x18\x02 \x01(\x0b\x32*.kessel.inventory.v1beta2.ConsistencyTokenR\x10\x63onsistencyTokenBr\n(org.project_kessel.api.inventory.v1beta2P\x01ZDgithub.com/project-kessel/inventory-api/api/kessel/inventory/v1beta2b\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Kessel
  module Inventory
    module V1beta2
      CheckSelfBulkResponseItem = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kessel.inventory.v1beta2.CheckSelfBulkResponseItem").msgclass
      CheckSelfBulkResponsePair = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kessel.inventory.v1beta2.CheckSelfBulkResponsePair").msgclass
      CheckSelfBulkResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kessel.inventory.v1beta2.CheckSelfBulkResponse").msgclass
    end
  end
end
