# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kessel/inventory/v1beta2/check_self_bulk_request.proto

require 'google/protobuf'

require 'buf/validate/validate_pb'
require 'kessel/inventory/v1beta2/resource_reference_pb'
require 'kessel/inventory/v1beta2/consistency_pb'


descriptor_data = "\n6kessel/inventory/v1beta2/check_self_bulk_request.proto\x12\x18kessel.inventory.v1beta2\x1a\x1b\x62uf/validate/validate.proto\x1a\x31kessel/inventory/v1beta2/resource_reference.proto\x1a*kessel/inventory/v1beta2/consistency.proto\"\x8c\x01\n\x18\x43heckSelfBulkRequestItem\x12K\n\x06object\x18\x01 \x01(\x0b\x32+.kessel.inventory.v1beta2.ResourceReferenceB\x06\xbaH\x03\xc8\x01\x01R\x06object\x12#\n\x08relation\x18\x02 \x01(\tB\x07\xbaH\x04r\x02\x10\x01R\x08relation\"\xcb\x01\n\x14\x43heckSelfBulkRequest\x12U\n\x05items\x18\x01 \x03(\x0b\x32\x32.kessel.inventory.v1beta2.CheckSelfBulkRequestItemB\x0b\xbaH\x08\x92\x01\x05\x08\x01\x10\xe8\x07R\x05items\x12L\n\x0b\x63onsistency\x18\x02 \x01(\x0b\x32%.kessel.inventory.v1beta2.ConsistencyH\x00R\x0b\x63onsistency\x88\x01\x01\x42\x0e\n\x0c_consistencyBr\n(org.project_kessel.api.inventory.v1beta2P\x01ZDgithub.com/project-kessel/inventory-api/api/kessel/inventory/v1beta2b\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Kessel
  module Inventory
    module V1beta2
      CheckSelfBulkRequestItem = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kessel.inventory.v1beta2.CheckSelfBulkRequestItem").msgclass
      CheckSelfBulkRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kessel.inventory.v1beta2.CheckSelfBulkRequest").msgclass
    end
  end
end
