# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kessel/inventory/v1beta2/check_for_update_bulk_response.proto

require 'google/protobuf'

require 'kessel/inventory/v1beta2/check_bulk_request_pb'
require 'kessel/inventory/v1beta2/consistency_token_pb'
require 'kessel/inventory/v1beta2/allowed_pb'
require 'buf/validate/validate_pb'
require 'google/rpc/status_pb'


descriptor_data = "\n=kessel/inventory/v1beta2/check_for_update_bulk_response.proto\x12\x18kessel.inventory.v1beta2\x1a\x31kessel/inventory/v1beta2/check_bulk_request.proto\x1a\x30kessel/inventory/v1beta2/consistency_token.proto\x1a&kessel/inventory/v1beta2/allowed.proto\x1a\x1b\x62uf/validate/validate.proto\x1a\x17google/rpc/status.proto\"]\n\x1e\x43heckForUpdateBulkResponseItem\x12;\n\x07\x61llowed\x18\x01 \x01(\x0e\x32!.kessel.inventory.v1beta2.AllowedR\x07\x61llowed\"\xf2\x01\n\x1e\x43heckForUpdateBulkResponsePair\x12H\n\x07request\x18\x01 \x01(\x0b\x32..kessel.inventory.v1beta2.CheckBulkRequestItemR\x07request\x12N\n\x04item\x18\x02 \x01(\x0b\x32\x38.kessel.inventory.v1beta2.CheckForUpdateBulkResponseItemH\x00R\x04item\x12*\n\x05\x65rror\x18\x03 \x01(\x0b\x32\x12.google.rpc.StatusH\x00R\x05\x65rrorB\n\n\x08response\"\xcf\x01\n\x1a\x43heckForUpdateBulkResponse\x12X\n\x05pairs\x18\x01 \x03(\x0b\x32\x38.kessel.inventory.v1beta2.CheckForUpdateBulkResponsePairB\x08\xbaH\x05\x92\x01\x02\x08\x01R\x05pairs\x12W\n\x11\x63onsistency_token\x18\x02 \x01(\x0b\x32*.kessel.inventory.v1beta2.ConsistencyTokenR\x10\x63onsistencyTokenBr\n(org.project_kessel.api.inventory.v1beta2P\x01ZDgithub.com/project-kessel/inventory-api/api/kessel/inventory/v1beta2b\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Kessel
  module Inventory
    module V1beta2
      CheckForUpdateBulkResponseItem = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kessel.inventory.v1beta2.CheckForUpdateBulkResponseItem").msgclass
      CheckForUpdateBulkResponsePair = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kessel.inventory.v1beta2.CheckForUpdateBulkResponsePair").msgclass
      CheckForUpdateBulkResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kessel.inventory.v1beta2.CheckForUpdateBulkResponse").msgclass
    end
  end
end
