# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kessel/inventory/v1beta2/report_resource_request.proto

require 'google/protobuf'

require 'kessel/inventory/v1beta2/resource_representations_pb'
require 'kessel/inventory/v1beta2/write_visibility_pb'
require 'buf/validate/validate_pb'


descriptor_data = "\n6kessel/inventory/v1beta2/report_resource_request.proto\x12\x18kessel.inventory.v1beta2\x1a\x37kessel/inventory/v1beta2/resource_representations.proto\x1a/kessel/inventory/v1beta2/write_visibility.proto\x1a\x1b\x62uf/validate/validate.proto\"\xbf\x03\n\x15ReportResourceRequest\x12&\n\x0cinventory_id\x18\x01 \x01(\tH\x00R\x0binventoryId\x88\x01\x01\x12-\n\x04type\x18\x02 \x01(\tB\x19\xbaH\x16r\x14\x10\x01\x32\x10^[A-Za-z0-9_-]+$R\x04type\x12>\n\rreporter_type\x18\x03 \x01(\tB\x19\xbaH\x16r\x14\x10\x01\x32\x10^[A-Za-z0-9_-]+$R\x0creporterType\x12\x39\n\x14reporter_instance_id\x18\x04 \x01(\tB\x07\xbaH\x04r\x02\x10\x01R\x12reporterInstanceId\x12\x63\n\x0frepresentations\x18\x05 \x01(\x0b\x32\x31.kessel.inventory.v1beta2.ResourceRepresentationsB\x06\xbaH\x03\xc8\x01\x01R\x0frepresentations\x12^\n\x10write_visibility\x18\x06 \x01(\x0e\x32).kessel.inventory.v1beta2.WriteVisibilityB\x08\xbaH\x05\x82\x01\x02\x10\x01R\x0fwriteVisibilityB\x0f\n\r_inventory_idBr\n(org.project_kessel.api.inventory.v1beta2P\x01ZDgithub.com/project-kessel/inventory-api/api/kessel/inventory/v1beta2b\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Kessel
  module Inventory
    module V1beta2
      ReportResourceRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kessel.inventory.v1beta2.ReportResourceRequest").msgclass
    end
  end
end
