# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kessel/inventory/v1beta2/report_resource_response.proto

require 'google/protobuf'


descriptor_data = "\n7kessel/inventory/v1beta2/report_resource_response.proto\x12\x18kessel.inventory.v1beta2\"\x18\n\x16ReportResourceResponseBr\n(org.project_kessel.api.inventory.v1beta2P\x01ZDgithub.com/project-kessel/inventory-api/api/kessel/inventory/v1beta2b\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Kessel
  module Inventory
    module V1beta2
      ReportResourceResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kessel.inventory.v1beta2.ReportResourceResponse").msgclass
    end
  end
end
