# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kessel/inventory/v1beta2/representation_metadata.proto

require 'google/protobuf'

require 'buf/validate/validate_pb'


descriptor_data = "\n6kessel/inventory/v1beta2/representation_metadata.proto\x12\x18kessel.inventory.v1beta2\x1a\x1b\x62uf/validate/validate.proto\"\xef\x01\n\x16RepresentationMetadata\x12\x33\n\x11local_resource_id\x18\x01 \x01(\tB\x07\xbaH\x04r\x02\x10\x01R\x0flocalResourceId\x12\"\n\x08\x61pi_href\x18\x02 \x01(\tB\x07\xbaH\x04r\x02\x10\x01R\x07\x61piHref\x12&\n\x0c\x63onsole_href\x18\x03 \x01(\tH\x00R\x0b\x63onsoleHref\x88\x01\x01\x12.\n\x10reporter_version\x18\x04 \x01(\tH\x01R\x0freporterVersion\x88\x01\x01\x42\x0f\n\r_console_hrefB\x13\n\x11_reporter_versionBr\n(org.project_kessel.api.inventory.v1beta2P\x01ZDgithub.com/project-kessel/inventory-api/api/kessel/inventory/v1beta2b\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Kessel
  module Inventory
    module V1beta2
      RepresentationMetadata = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kessel.inventory.v1beta2.RepresentationMetadata").msgclass
    end
  end
end
