# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kessel/inventory/v1beta2/representation_type.proto

require 'google/protobuf'

require 'buf/validate/validate_pb'


descriptor_data = "\n2kessel/inventory/v1beta2/representation_type.proto\x12\x18kessel.inventory.v1beta2\x1a\x1b\x62uf/validate/validate.proto\"\xa7\x01\n\x12RepresentationType\x12=\n\rresource_type\x18\x01 \x01(\tB\x18\xbaH\x15r\x13\x10\x01\x32\x0f^[A-Za-z0-9_]+$R\x0cresourceType\x12@\n\rreporter_type\x18\x02 \x01(\tB\x16\xbaH\x13r\x11\x32\x0f^[A-Za-z0-9_]+$H\x00R\x0creporterType\x88\x01\x01\x42\x10\n\x0e_reporter_typeBr\n(org.project_kessel.api.inventory.v1beta2P\x01ZDgithub.com/project-kessel/inventory-api/api/kessel/inventory/v1beta2b\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Kessel
  module Inventory
    module V1beta2
      RepresentationType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kessel.inventory.v1beta2.RepresentationType").msgclass
    end
  end
end
