# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kessel/inventory/v1beta2/resource_reference.proto

require 'google/protobuf'

require 'buf/validate/validate_pb'
require 'kessel/inventory/v1beta2/reporter_reference_pb'


descriptor_data = "\n1kessel/inventory/v1beta2/resource_reference.proto\x12\x18kessel.inventory.v1beta2\x1a\x1b\x62uf/validate/validate.proto\x1a\x31kessel/inventory/v1beta2/reporter_reference.proto\"\xd7\x01\n\x11ResourceReference\x12=\n\rresource_type\x18\x01 \x01(\tB\x18\xbaH\x15r\x13\x10\x01\x32\x0f^[A-Za-z0-9_]+$R\x0cresourceType\x12(\n\x0bresource_id\x18\x02 \x01(\tB\x07\xbaH\x04r\x02\x10\x01R\nresourceId\x12L\n\x08reporter\x18\x03 \x01(\x0b\x32+.kessel.inventory.v1beta2.ReporterReferenceH\x00R\x08reporter\x88\x01\x01\x42\x0b\n\t_reporterBr\n(org.project_kessel.api.inventory.v1beta2P\x01ZDgithub.com/project-kessel/inventory-api/api/kessel/inventory/v1beta2b\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Kessel
  module Inventory
    module V1beta2
      ResourceReference = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kessel.inventory.v1beta2.ResourceReference").msgclass
    end
  end
end
