# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kessel/inventory/v1beta2/resource_representations.proto

require 'google/protobuf'

require 'google/protobuf/struct_pb'
require 'kessel/inventory/v1beta2/representation_metadata_pb'
require 'buf/validate/validate_pb'


descriptor_data = "\n7kessel/inventory/v1beta2/resource_representations.proto\x12\x18kessel.inventory.v1beta2\x1a\x1cgoogle/protobuf/struct.proto\x1a\x36kessel/inventory/v1beta2/representation_metadata.proto\x1a\x1b\x62uf/validate/validate.proto\"\xf7\x01\n\x17ResourceRepresentations\x12T\n\x08metadata\x18\x01 \x01(\x0b\x32\x30.kessel.inventory.v1beta2.RepresentationMetadataB\x06\xbaH\x03\xc8\x01\x01R\x08metadata\x12\x34\n\x06\x63ommon\x18\x02 \x01(\x0b\x32\x17.google.protobuf.StructH\x00R\x06\x63ommon\x88\x01\x01\x12\x38\n\x08reporter\x18\x03 \x01(\x0b\x32\x17.google.protobuf.StructH\x01R\x08reporter\x88\x01\x01\x42\t\n\x07_commonB\x0b\n\t_reporterBr\n(org.project_kessel.api.inventory.v1beta2P\x01ZDgithub.com/project-kessel/inventory-api/api/kessel/inventory/v1beta2b\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Kessel
  module Inventory
    module V1beta2
      ResourceRepresentations = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kessel.inventory.v1beta2.ResourceRepresentations").msgclass
    end
  end
end
