# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kessel/inventory/v1beta2/response_pagination.proto

require 'google/protobuf'


descriptor_data = "\n2kessel/inventory/v1beta2/response_pagination.proto\x12\x18kessel.inventory.v1beta2\"C\n\x12ResponsePagination\x12-\n\x12\x63ontinuation_token\x18\x01 \x01(\tR\x11\x63ontinuationTokenBr\n(org.project_kessel.api.inventory.v1beta2P\x01ZDgithub.com/project-kessel/inventory-api/api/kessel/inventory/v1beta2b\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Kessel
  module Inventory
    module V1beta2
      ResponsePagination = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kessel.inventory.v1beta2.ResponsePagination").msgclass
    end
  end
end
