# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kessel/inventory/v1beta2/streamed_list_subjects_request.proto

require 'google/protobuf'

require 'buf/validate/validate_pb'
require 'kessel/inventory/v1beta2/resource_reference_pb'
require 'kessel/inventory/v1beta2/representation_type_pb'
require 'kessel/inventory/v1beta2/request_pagination_pb'
require 'kessel/inventory/v1beta2/consistency_pb'


descriptor_data = "\n=kessel/inventory/v1beta2/streamed_list_subjects_request.proto\x12\x18kessel.inventory.v1beta2\x1a\x1b\x62uf/validate/validate.proto\x1a\x31kessel/inventory/v1beta2/resource_reference.proto\x1a\x32kessel/inventory/v1beta2/representation_type.proto\x1a\x31kessel/inventory/v1beta2/request_pagination.proto\x1a*kessel/inventory/v1beta2/consistency.proto\"\xf0\x03\n\x1bStreamedListSubjectsRequest\x12O\n\x08resource\x18\x01 \x01(\x0b\x32+.kessel.inventory.v1beta2.ResourceReferenceB\x06\xbaH\x03\xc8\x01\x01R\x08resource\x12#\n\x08relation\x18\x02 \x01(\tB\x07\xbaH\x04r\x02\x10\x01R\x08relation\x12W\n\x0csubject_type\x18\x03 \x01(\x0b\x32,.kessel.inventory.v1beta2.RepresentationTypeB\x06\xbaH\x03\xc8\x01\x01R\x0bsubjectType\x12.\n\x10subject_relation\x18\x04 \x01(\tH\x00R\x0fsubjectRelation\x88\x01\x01\x12P\n\npagination\x18\x05 \x01(\x0b\x32+.kessel.inventory.v1beta2.RequestPaginationH\x01R\npagination\x88\x01\x01\x12L\n\x0b\x63onsistency\x18\x06 \x01(\x0b\x32%.kessel.inventory.v1beta2.ConsistencyH\x02R\x0b\x63onsistency\x88\x01\x01\x42\x13\n\x11_subject_relationB\r\n\x0b_paginationB\x0e\n\x0c_consistencyBr\n(org.project_kessel.api.inventory.v1beta2P\x01ZDgithub.com/project-kessel/inventory-api/api/kessel/inventory/v1beta2b\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Kessel
  module Inventory
    module V1beta2
      StreamedListSubjectsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kessel.inventory.v1beta2.StreamedListSubjectsRequest").msgclass
    end
  end
end
