# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kessel/inventory/v1beta2/streamed_list_objects_response.proto

require 'google/protobuf'

require 'kessel/inventory/v1beta2/resource_reference_pb'
require 'kessel/inventory/v1beta2/response_pagination_pb'
require 'kessel/inventory/v1beta2/consistency_token_pb'


descriptor_data = "\n=kessel/inventory/v1beta2/streamed_list_objects_response.proto\x12\x18kessel.inventory.v1beta2\x1a\x31kessel/inventory/v1beta2/resource_reference.proto\x1a\x32kessel/inventory/v1beta2/response_pagination.proto\x1a\x30kessel/inventory/v1beta2/consistency_token.proto\"\x89\x02\n\x1bStreamedListObjectsResponse\x12\x43\n\x06object\x18\x01 \x01(\x0b\x32+.kessel.inventory.v1beta2.ResourceReferenceR\x06object\x12L\n\npagination\x18\x02 \x01(\x0b\x32,.kessel.inventory.v1beta2.ResponsePaginationR\npagination\x12W\n\x11\x63onsistency_token\x18\x03 \x01(\x0b\x32*.kessel.inventory.v1beta2.ConsistencyTokenR\x10\x63onsistencyTokenBr\n(org.project_kessel.api.inventory.v1beta2P\x01ZDgithub.com/project-kessel/inventory-api/api/kessel/inventory/v1beta2b\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Kessel
  module Inventory
    module V1beta2
      StreamedListObjectsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kessel.inventory.v1beta2.StreamedListObjectsResponse").msgclass
    end
  end
end
