# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: kessel/inventory/v1beta2/tuple_service.proto for package 'kessel.inventory.v1beta2'

require 'grpc'
require 'kessel/inventory/v1beta2/tuple_service_pb'

module Kessel
  module Inventory
    module V1beta2
      module KesselTupleService
        # DEPRECATED: KesselTupleService provides legacy tuple-layer operations.
        # This service exists only for RBAC backward compatibility and will be removed.
        # All endpoints are marked deprecated. Do not add new consumers.
        # Use KesselInventoryService's ReportResource for new integrations.
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'kessel.inventory.v1beta2.KesselTupleService'

          # DEPRECATED: CreateTuples creates relationship tuples.
          # This endpoint exists only for RBAC backward compatibility.
          # Use ReportResource instead for new code.
          rpc :CreateTuples, ::Kessel::Inventory::V1beta2::CreateTuplesRequest, ::Kessel::Inventory::V1beta2::CreateTuplesResponse
          # DEPRECATED: DeleteTuples deletes relationship tuples.
          # This endpoint exists only for RBAC backward compatibility.
          # Use DeleteResource instead for new code.
          rpc :DeleteTuples, ::Kessel::Inventory::V1beta2::DeleteTuplesRequest, ::Kessel::Inventory::V1beta2::DeleteTuplesResponse
          # DEPRECATED: ReadTuples reads relationship tuples.
          # This endpoint exists only for RBAC backward compatibility.
          # Use StreamedListObjects/StreamedListSubjects instead for new code.
          rpc :ReadTuples, ::Kessel::Inventory::V1beta2::ReadTuplesRequest, stream(::Kessel::Inventory::V1beta2::ReadTuplesResponse)
          # DEPRECATED: AcquireLock acquires a distributed lock.
          # This endpoint exists only for RBAC backward compatibility.
          rpc :AcquireLock, ::Kessel::Inventory::V1beta2::AcquireLockRequest, ::Kessel::Inventory::V1beta2::AcquireLockResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
