# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kessel/inventory/v1beta2/write_visibility.proto

require 'google/protobuf'


descriptor_data = "\n/kessel/inventory/v1beta2/write_visibility.proto\x12\x18kessel.inventory.v1beta2*X\n\x0fWriteVisibility\x12 \n\x1cWRITE_VISIBILITY_UNSPECIFIED\x10\x00\x12\x14\n\x10MINIMIZE_LATENCY\x10\x01\x12\r\n\tIMMEDIATE\x10\x02\x42r\n(org.project_kessel.api.inventory.v1beta2P\x01ZDgithub.com/project-kessel/inventory-api/api/kessel/inventory/v1beta2b\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Kessel
  module Inventory
    module V1beta2
      WriteVisibility = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kessel.inventory.v1beta2.WriteVisibility").enummodule
    end
  end
end
