# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: kessel/inventory/v1/health.proto for package 'kessel.inventory.v1'

require 'grpc'
require 'kessel/inventory/v1/health_pb'

module Kessel
  module Inventory
    module V1
      module KesselInventoryHealthService
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'kessel.inventory.v1.KesselInventoryHealthService'

          rpc :GetLivez, ::Kessel::Inventory::V1::GetLivezRequest, ::Kessel::Inventory::V1::GetLivezResponse
          rpc :GetReadyz, ::Kessel::Inventory::V1::GetReadyzRequest, ::Kessel::Inventory::V1::GetReadyzResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
