# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kessel/inventory/v1/health.proto

require 'google/protobuf'

require 'google/api/annotations_pb'


descriptor_data = "\n kessel/inventory/v1/health.proto\x12\x13kessel.inventory.v1\x1a\x1cgoogle/api/annotations.proto\"\x11\n\x0fGetLivezRequest\">\n\x10GetLivezResponse\x12\x16\n\x06status\x18\x01 \x01(\tR\x06status\x12\x12\n\x04\x63ode\x18\x02 \x01(\rR\x04\x63ode\"\x12\n\x10GetReadyzRequest\"?\n\x11GetReadyzResponse\x12\x16\n\x06status\x18\x01 \x01(\tR\x06status\x12\x12\n\x04\x63ode\x18\x02 \x01(\rR\x04\x63ode2\x96\x02\n\x1cKesselInventoryHealthService\x12x\n\x08GetLivez\x12$.kessel.inventory.v1.GetLivezRequest\x1a%.kessel.inventory.v1.GetLivezResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/api/inventory/v1/livez\x12|\n\tGetReadyz\x12%.kessel.inventory.v1.GetReadyzRequest\x1a&.kessel.inventory.v1.GetReadyzResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/api/inventory/v1/readyzBh\n#org.project_kessel.api.inventory.v1P\x01Z?github.com/project-kessel/inventory-api/api/kessel/inventory/v1b\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Kessel
  module Inventory
    module V1
      GetLivezRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kessel.inventory.v1.GetLivezRequest").msgclass
      GetLivezResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kessel.inventory.v1.GetLivezResponse").msgclass
      GetReadyzRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kessel.inventory.v1.GetReadyzRequest").msgclass
      GetReadyzResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kessel.inventory.v1.GetReadyzResponse").msgclass
    end
  end
end
