# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kessel/inventory/v1beta1/relationships/k8spolicy_ispropagatedto_k8scluster_detail.proto

require 'google/protobuf'

require 'google/api/field_behavior_pb'
require 'buf/validate/validate_pb'


descriptor_data = "\nWkessel/inventory/v1beta1/relationships/k8spolicy_ispropagatedto_k8scluster_detail.proto\x12&kessel.inventory.v1beta1.relationships\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1b\x62uf/validate/validate.proto\"\xde\x02\n\'K8SPolicyIsPropagatedToK8SClusterDetail\x12,\n\rk8s_policy_id\x18\xb8\xb1\xcek \x01(\tB\x03\xe0\x41\x03R\rk8s_policy_id\x12.\n\x0ek8s_cluster_id\x18\x80\xcb\xc9r \x01(\tB\x03\xe0\x41\x03R\x0ek8s_cluster_id\x12~\n\x06status\x18\x8f\xe0\xc8\xa9\x01 \x01(\x0e\x32V.kessel.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetail.StatusB\n\xbaH\x07\x82\x01\x04\x10\x01 \x00R\x06status\"U\n\x06Status\x12\x16\n\x12STATUS_UNSPECIFIED\x10\x00\x12\x10\n\x0cSTATUS_OTHER\x10\x01\x12\x0e\n\nVIOLATIONS\x10\x02\x12\x11\n\rNO_VIOLATIONS\x10\x03\x42\xbc\x01\n6org.project_kessel.api.inventory.v1beta1.relationshipsB,K8SPolicyIsPropagatedToK8SClusterDetailProtoP\x01ZRgithub.com/project-kessel/inventory-api/api/kessel/inventory/v1beta1/relationshipsb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Kessel
  module Inventory
    module V1beta1
      module Relationships
        K8SPolicyIsPropagatedToK8SClusterDetail = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kessel.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetail").msgclass
        K8SPolicyIsPropagatedToK8SClusterDetail::Status = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kessel.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetail.Status").enummodule
      end
    end
  end
end
