# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: kessel/inventory/v1beta1/relationships/k8spolicy_ispropagatedto_k8scluster_service.proto for package 'kessel.inventory.v1beta1.relationships'

require 'grpc'
require 'kessel/inventory/v1beta1/relationships/k8spolicy_ispropagatedto_k8scluster_service_pb'

module Kessel
  module Inventory
    module V1beta1
      module Relationships
        module KesselK8SPolicyIsPropagatedToK8SClusterService
          class Service

            include ::GRPC::GenericService

            self.marshal_class_method = :encode
            self.unmarshal_class_method = :decode
            self.service_name = 'kessel.inventory.v1beta1.relationships.KesselK8SPolicyIsPropagatedToK8SClusterService'

            rpc :CreateK8SPolicyIsPropagatedToK8SCluster, ::Kessel::Inventory::V1beta1::Relationships::CreateK8SPolicyIsPropagatedToK8SClusterRequest, ::Kessel::Inventory::V1beta1::Relationships::CreateK8SPolicyIsPropagatedToK8SClusterResponse
            rpc :UpdateK8SPolicyIsPropagatedToK8SCluster, ::Kessel::Inventory::V1beta1::Relationships::UpdateK8SPolicyIsPropagatedToK8SClusterRequest, ::Kessel::Inventory::V1beta1::Relationships::UpdateK8SPolicyIsPropagatedToK8SClusterResponse
            rpc :DeleteK8SPolicyIsPropagatedToK8SCluster, ::Kessel::Inventory::V1beta1::Relationships::DeleteK8SPolicyIsPropagatedToK8SClusterRequest, ::Kessel::Inventory::V1beta1::Relationships::DeleteK8SPolicyIsPropagatedToK8SClusterResponse
          end

          Stub = Service.rpc_stub_class
        end
      end
    end
  end
end
