# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kessel/inventory/v1beta1/relationships/k8spolicy_ispropagatedto_k8scluster.proto

require 'google/protobuf'

require 'kessel/inventory/v1beta1/relationships/metadata_pb'
require 'kessel/inventory/v1beta1/relationships/reporter_data_pb'
require 'kessel/inventory/v1beta1/relationships/k8spolicy_ispropagatedto_k8scluster_detail_pb'
require 'buf/validate/validate_pb'


descriptor_data = "\nPkessel/inventory/v1beta1/relationships/k8spolicy_ispropagatedto_k8scluster.proto\x12&kessel.inventory.v1beta1.relationships\x1a\x35kessel/inventory/v1beta1/relationships/metadata.proto\x1a:kessel/inventory/v1beta1/relationships/reporter_data.proto\x1aWkessel/inventory/v1beta1/relationships/k8spolicy_ispropagatedto_k8scluster_detail.proto\x1a\x1b\x62uf/validate/validate.proto\"\xeb\x02\n!K8SPolicyIsPropagatedToK8SCluster\x12T\n\x08metadata\x18\x01 \x01(\x0b\x32\x30.kessel.inventory.v1beta1.relationships.MetadataB\x06\xbaH\x03\xd8\x01\x03R\x08metadata\x12\x65\n\rreporter_data\x18\xc9\xd0\xfat \x01(\x0b\x32\x34.kessel.inventory.v1beta1.relationships.ReporterDataB\x06\xbaH\x03\xc8\x01\x01R\rreporter_data\x12\x88\x01\n\x11relationship_data\x18\xcb\xc7\x81\x01 \x01(\x0b\x32O.kessel.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetailB\x06\xbaH\x03\xc8\x01\x01R\x11relationship_dataB\xb6\x01\n6org.project_kessel.api.inventory.v1beta1.relationshipsB&K8SPolicyIsPropagatedToK8SClusterProtoP\x01ZRgithub.com/project-kessel/inventory-api/api/kessel/inventory/v1beta1/relationshipsb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Kessel
  module Inventory
    module V1beta1
      module Relationships
        K8SPolicyIsPropagatedToK8SCluster = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kessel.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SCluster").msgclass
      end
    end
  end
end
