# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kessel/inventory/v1beta1/relationships/metadata.proto

require 'google/protobuf'

require 'buf/validate/validate_pb'
require 'google/api/field_behavior_pb'
require 'google/protobuf/timestamp_pb'


descriptor_data = "\n5kessel/inventory/v1beta1/relationships/metadata.proto\x12&kessel.inventory.v1beta1.relationships\x1a\x1b\x62uf/validate/validate.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbe\x02\n\x08Metadata\x12\x14\n\x02id\x18\x9c\x1a \x01(\tB\x03\xe0\x41\x03R\x02id\x12\x34\n\x11relationship_type\x18\xe4\xe9\xd7w \x01(\tB\x03\xe0\x41\x03R\x11relationship_type\x12@\n\ncreated_at\x18\xc8\x1a \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x03\xe0\x41\x03R\ncreated_at\x12@\n\nupdated_at\x18\xc9\x1a \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x03\xe0\x41\x03R\nupdated_at\x12@\n\ndeleted_at\x18\xca\x1a \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x03\xe0\x41\x03R\ndeleted_at\x12 \n\x06org_id\x18\xac\x1b \x01(\tB\x07\xbaH\x04r\x02\x10\x01R\x06org_idB\x8e\x01\n6org.project_kessel.api.inventory.v1beta1.relationshipsP\x01ZRgithub.com/project-kessel/inventory-api/api/kessel/inventory/v1beta1/relationshipsb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Kessel
  module Inventory
    module V1beta1
      module Relationships
        Metadata = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kessel.inventory.v1beta1.relationships.Metadata").msgclass
      end
    end
  end
end
