# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kessel/inventory/v1beta1/relationships/reporter_data.proto

require 'google/protobuf'

require 'google/api/field_behavior_pb'
require 'google/protobuf/timestamp_pb'
require 'buf/validate/validate_pb'


descriptor_data = "\n:kessel/inventory/v1beta1/relationships/reporter_data.proto\x12&kessel.inventory.v1beta1.relationships\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1b\x62uf/validate/validate.proto\"\x94\x05\n\x0cReporterData\x12w\n\rreporter_type\x18\xd9\x8f\x99u \x01(\x0e\x32\x41.kessel.inventory.v1beta1.relationships.ReporterData.ReporterTypeB\x0b\xbaH\x08\x82\x01\x05\x10\x01\"\x01\x00R\rreporter_type\x12:\n\x14reporter_instance_id\x18\xba\xd5\xfar \x01(\tB\x03\xe0\x41\x03R\x14reporter_instance_id\x12.\n\x10reporter_version\x18\xfb\xee\xc8\x80\x01 \x01(\tR\x10reporter_version\x12J\n\x0e\x66irst_reported\x18\x81\xed\xce\x06 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x03\xe0\x41\x03R\x0e\x66irst_reported\x12I\n\rlast_reported\x18\x8c\x9d\x90\xd0\x01 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x03\xe0\x41\x03R\rlast_reported\x12I\n\x19subject_local_resource_id\x18\xbe\xb8\xd9\xf2\x01 \x01(\tB\x07\xbaH\x04r\x02\x10\x01R\x19subject_local_resource_id\x12G\n\x18object_local_resource_id\x18\xbf\xb8\xd9\xf2\x01 \x01(\tB\x07\xbaH\x04r\x02\x10\x01R\x18object_local_resource_id\"t\n\x0cReporterType\x12\x1d\n\x19REPORTER_TYPE_UNSPECIFIED\x10\x00\x12\x17\n\x13REPORTER_TYPE_OTHER\x10\x01\x12\x07\n\x03\x41\x43M\x10\x02\x12\x07\n\x03HBI\x10\x03\x12\x07\n\x03OCM\x10\x04\x12\x11\n\rNOTIFICATIONS\x10\x05\x42\x8e\x01\n6org.project_kessel.api.inventory.v1beta1.relationshipsP\x01ZRgithub.com/project-kessel/inventory-api/api/kessel/inventory/v1beta1/relationshipsb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Kessel
  module Inventory
    module V1beta1
      module Relationships
        ReporterData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kessel.inventory.v1beta1.relationships.ReporterData").msgclass
        ReporterData::ReporterType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kessel.inventory.v1beta1.relationships.ReporterData.ReporterType").enummodule
      end
    end
  end
end
