# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kessel/inventory/v1beta1/resources/k8s_cluster.proto

require 'google/protobuf'

require 'buf/validate/validate_pb'
require 'kessel/inventory/v1beta1/resources/k8s_cluster_detail_pb'
require 'kessel/inventory/v1beta1/resources/metadata_pb'
require 'kessel/inventory/v1beta1/resources/reporter_data_pb'


descriptor_data = "\n4kessel/inventory/v1beta1/resources/k8s_cluster.proto\x12\"kessel.inventory.v1beta1.resources\x1a\x1b\x62uf/validate/validate.proto\x1a;kessel/inventory/v1beta1/resources/k8s_cluster_detail.proto\x1a\x31kessel/inventory/v1beta1/resources/metadata.proto\x1a\x36kessel/inventory/v1beta1/resources/reporter_data.proto\"\xa0\x02\n\nK8sCluster\x12H\n\x08metadata\x18\x01 \x01(\x0b\x32,.kessel.inventory.v1beta1.resources.MetadataR\x08metadata\x12\x61\n\rreporter_data\x18\xc8\xd0\xfat \x01(\x0b\x32\x30.kessel.inventory.v1beta1.resources.ReporterDataB\x06\xbaH\x03\xc8\x01\x01R\rreporter_data\x12\x65\n\rresource_data\x18\xca\xc7\x81\x01 \x01(\x0b\x32\x34.kessel.inventory.v1beta1.resources.K8sClusterDetailB\x06\xbaH\x03\xc8\x01\x01R\rresource_dataB\x97\x01\n2org.project_kessel.api.inventory.v1beta1.resourcesB\x0fK8sClusterProtoP\x01ZNgithub.com/project-kessel/inventory-api/api/kessel/inventory/v1beta1/resourcesb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Kessel
  module Inventory
    module V1beta1
      module Resources
        K8sCluster = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kessel.inventory.v1beta1.resources.K8sCluster").msgclass
      end
    end
  end
end
