# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: kessel/inventory/v1beta1/resources/k8s_clusters_service.proto for package 'kessel.inventory.v1beta1.resources'

require 'grpc'
require 'kessel/inventory/v1beta1/resources/k8s_clusters_service_pb'

module Kessel
  module Inventory
    module V1beta1
      module Resources
        module KesselK8sClusterService
          class Service

            include ::GRPC::GenericService

            self.marshal_class_method = :encode
            self.unmarshal_class_method = :decode
            self.service_name = 'kessel.inventory.v1beta1.resources.KesselK8sClusterService'

            rpc :CreateK8sCluster, ::Kessel::Inventory::V1beta1::Resources::CreateK8sClusterRequest, ::Kessel::Inventory::V1beta1::Resources::CreateK8sClusterResponse
            rpc :UpdateK8sCluster, ::Kessel::Inventory::V1beta1::Resources::UpdateK8sClusterRequest, ::Kessel::Inventory::V1beta1::Resources::UpdateK8sClusterResponse
            rpc :DeleteK8sCluster, ::Kessel::Inventory::V1beta1::Resources::DeleteK8sClusterRequest, ::Kessel::Inventory::V1beta1::Resources::DeleteK8sClusterResponse
          end

          Stub = Service.rpc_stub_class
        end
      end
    end
  end
end
