# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kessel/inventory/v1beta1/resources/k8s_clusters_service.proto

require 'google/protobuf'

require 'google/api/annotations_pb'
require 'buf/validate/validate_pb'
require 'kessel/inventory/v1beta1/resources/k8s_cluster_pb'
require 'kessel/inventory/v1beta1/resources/reporter_data_pb'


descriptor_data = "\n=kessel/inventory/v1beta1/resources/k8s_clusters_service.proto\x12\"kessel.inventory.v1beta1.resources\x1a\x1cgoogle/api/annotations.proto\x1a\x1b\x62uf/validate/validate.proto\x1a\x34kessel/inventory/v1beta1/resources/k8s_cluster.proto\x1a\x36kessel/inventory/v1beta1/resources/reporter_data.proto\"k\n\x17\x43reateK8sClusterRequest\x12P\n\x0bk8s_cluster\x18\x01 \x01(\x0b\x32..kessel.inventory.v1beta1.resources.K8sClusterR\x0bk8s_cluster\"\x1a\n\x18\x43reateK8sClusterResponse\"k\n\x17UpdateK8sClusterRequest\x12P\n\x0bk8s_cluster\x18\x01 \x01(\x0b\x32..kessel.inventory.v1beta1.resources.K8sClusterR\x0bk8s_cluster\"\x1a\n\x18UpdateK8sClusterResponse\"y\n\x17\x44\x65leteK8sClusterRequest\x12^\n\rreporter_data\x18\x01 \x01(\x0b\x32\x30.kessel.inventory.v1beta1.resources.ReporterDataB\x06\xbaH\x03\xc8\x01\x01R\rreporter_data\"\x1a\n\x18\x44\x65leteK8sClusterResponse2\xf7\x04\n\x17KesselK8sClusterService\x12\xc7\x01\n\x10\x43reateK8sCluster\x12;.kessel.inventory.v1beta1.resources.CreateK8sClusterRequest\x1a<.kessel.inventory.v1beta1.resources.CreateK8sClusterResponse\"8\x82\xd3\xe4\x93\x02\x32\"-/api/inventory/v1beta1/resources/k8s-clusters:\x01*\x12\xc7\x01\n\x10UpdateK8sCluster\x12;.kessel.inventory.v1beta1.resources.UpdateK8sClusterRequest\x1a<.kessel.inventory.v1beta1.resources.UpdateK8sClusterResponse\"8\x82\xd3\xe4\x93\x02\x32\x1a-/api/inventory/v1beta1/resources/k8s-clusters:\x01*\x12\xc7\x01\n\x10\x44\x65leteK8sCluster\x12;.kessel.inventory.v1beta1.resources.DeleteK8sClusterRequest\x1a<.kessel.inventory.v1beta1.resources.DeleteK8sClusterResponse\"8\x82\xd3\xe4\x93\x02\x32*-/api/inventory/v1beta1/resources/k8s-clusters:\x01*B\x86\x01\n2org.project_kessel.api.inventory.v1beta1.resourcesP\x01ZNgithub.com/project-kessel/inventory-api/api/kessel/inventory/v1beta1/resourcesb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Kessel
  module Inventory
    module V1beta1
      module Resources
        CreateK8sClusterRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kessel.inventory.v1beta1.resources.CreateK8sClusterRequest").msgclass
        CreateK8sClusterResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kessel.inventory.v1beta1.resources.CreateK8sClusterResponse").msgclass
        UpdateK8sClusterRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kessel.inventory.v1beta1.resources.UpdateK8sClusterRequest").msgclass
        UpdateK8sClusterResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kessel.inventory.v1beta1.resources.UpdateK8sClusterResponse").msgclass
        DeleteK8sClusterRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kessel.inventory.v1beta1.resources.DeleteK8sClusterRequest").msgclass
        DeleteK8sClusterResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kessel.inventory.v1beta1.resources.DeleteK8sClusterResponse").msgclass
      end
    end
  end
end
