# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kessel/inventory/v1beta1/resources/k8s_policies_service.proto

require 'google/protobuf'

require 'google/api/annotations_pb'
require 'buf/validate/validate_pb'
require 'kessel/inventory/v1beta1/resources/k8s_policy_pb'
require 'kessel/inventory/v1beta1/resources/reporter_data_pb'


descriptor_data = "\n=kessel/inventory/v1beta1/resources/k8s_policies_service.proto\x12\"kessel.inventory.v1beta1.resources\x1a\x1cgoogle/api/annotations.proto\x1a\x1b\x62uf/validate/validate.proto\x1a\x33kessel/inventory/v1beta1/resources/k8s_policy.proto\x1a\x36kessel/inventory/v1beta1/resources/reporter_data.proto\"o\n\x16\x43reateK8sPolicyRequest\x12U\n\nk8s_policy\x18\x01 \x01(\x0b\x32-.kessel.inventory.v1beta1.resources.K8sPolicyB\x06\xbaH\x03\xc8\x01\x01R\nk8s_policy\"\x19\n\x17\x43reateK8sPolicyResponse\"o\n\x16UpdateK8sPolicyRequest\x12U\n\nk8s_policy\x18\x01 \x01(\x0b\x32-.kessel.inventory.v1beta1.resources.K8sPolicyB\x06\xbaH\x03\xc8\x01\x01R\nk8s_policy\"\x19\n\x17UpdateK8sPolicyResponse\"x\n\x16\x44\x65leteK8sPolicyRequest\x12^\n\rreporter_data\x18\x01 \x01(\x0b\x32\x30.kessel.inventory.v1beta1.resources.ReporterDataB\x06\xbaH\x03\xc8\x01\x01R\rreporter_data\"\x19\n\x17\x44\x65leteK8sPolicyResponse2\xed\x04\n\x16KesselK8sPolicyService\x12\xc4\x01\n\x0f\x43reateK8sPolicy\x12:.kessel.inventory.v1beta1.resources.CreateK8sPolicyRequest\x1a;.kessel.inventory.v1beta1.resources.CreateK8sPolicyResponse\"8\x82\xd3\xe4\x93\x02\x32\"-/api/inventory/v1beta1/resources/k8s-policies:\x01*\x12\xc4\x01\n\x0fUpdateK8sPolicy\x12:.kessel.inventory.v1beta1.resources.UpdateK8sPolicyRequest\x1a;.kessel.inventory.v1beta1.resources.UpdateK8sPolicyResponse\"8\x82\xd3\xe4\x93\x02\x32\x1a-/api/inventory/v1beta1/resources/k8s-policies:\x01*\x12\xc4\x01\n\x0f\x44\x65leteK8sPolicy\x12:.kessel.inventory.v1beta1.resources.DeleteK8sPolicyRequest\x1a;.kessel.inventory.v1beta1.resources.DeleteK8sPolicyResponse\"8\x82\xd3\xe4\x93\x02\x32*-/api/inventory/v1beta1/resources/k8s-policies:\x01*B\x86\x01\n2org.project_kessel.api.inventory.v1beta1.resourcesP\x01ZNgithub.com/project-kessel/inventory-api/api/kessel/inventory/v1beta1/resourcesb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Kessel
  module Inventory
    module V1beta1
      module Resources
        CreateK8sPolicyRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kessel.inventory.v1beta1.resources.CreateK8sPolicyRequest").msgclass
        CreateK8sPolicyResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kessel.inventory.v1beta1.resources.CreateK8sPolicyResponse").msgclass
        UpdateK8sPolicyRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kessel.inventory.v1beta1.resources.UpdateK8sPolicyRequest").msgclass
        UpdateK8sPolicyResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kessel.inventory.v1beta1.resources.UpdateK8sPolicyResponse").msgclass
        DeleteK8sPolicyRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kessel.inventory.v1beta1.resources.DeleteK8sPolicyRequest").msgclass
        DeleteK8sPolicyResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kessel.inventory.v1beta1.resources.DeleteK8sPolicyResponse").msgclass
      end
    end
  end
end
