# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kessel/inventory/v1beta1/resources/k8s_policy_detail.proto

require 'google/protobuf'

require 'buf/validate/validate_pb'


descriptor_data = "\n:kessel/inventory/v1beta1/resources/k8s_policy_detail.proto\x12\"kessel.inventory.v1beta1.resources\x1a\x1b\x62uf/validate/validate.proto\"\x80\x02\n\x0fK8sPolicyDetail\x12\x1e\n\x08\x64isabled\x18\xfd\xf4\x98\x81\x01 \x01(\x08R\x08\x64isabled\x12\x66\n\x08severity\x18\x80\xa6\xf4\xc0\x01 \x01(\x0e\x32<.kessel.inventory.v1beta1.resources.K8sPolicyDetail.SeverityB\x08\xbaH\x05\x82\x01\x02\x10\x01R\x08severity\"e\n\x08Severity\x12\x18\n\x14SEVERITY_UNSPECIFIED\x10\x00\x12\x12\n\x0eSEVERITY_OTHER\x10\x01\x12\x07\n\x03LOW\x10\x02\x12\n\n\x06MEDIUM\x10\x03\x12\x08\n\x04HIGH\x10\x04\x12\x0c\n\x08\x43RITICAL\x10\x05\x42\x9c\x01\n2org.project_kessel.api.inventory.v1beta1.resourcesB\x14K8sPolicyDetailProtoP\x01ZNgithub.com/project-kessel/inventory-api/api/kessel/inventory/v1beta1/resourcesb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Kessel
  module Inventory
    module V1beta1
      module Resources
        K8sPolicyDetail = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kessel.inventory.v1beta1.resources.K8sPolicyDetail").msgclass
        K8sPolicyDetail::Severity = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kessel.inventory.v1beta1.resources.K8sPolicyDetail.Severity").enummodule
      end
    end
  end
end
