# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: kessel/inventory/v1beta1/resources/k8s_policies_service.proto for package 'kessel.inventory.v1beta1.resources'

require 'grpc'
require 'kessel/inventory/v1beta1/resources/k8s_policies_service_pb'

module Kessel
  module Inventory
    module V1beta1
      module Resources
        module KesselK8sPolicyService
          class Service

            include ::GRPC::GenericService

            self.marshal_class_method = :encode
            self.unmarshal_class_method = :decode
            self.service_name = 'kessel.inventory.v1beta1.resources.KesselK8sPolicyService'

            rpc :CreateK8sPolicy, ::Kessel::Inventory::V1beta1::Resources::CreateK8sPolicyRequest, ::Kessel::Inventory::V1beta1::Resources::CreateK8sPolicyResponse
            rpc :UpdateK8sPolicy, ::Kessel::Inventory::V1beta1::Resources::UpdateK8sPolicyRequest, ::Kessel::Inventory::V1beta1::Resources::UpdateK8sPolicyResponse
            rpc :DeleteK8sPolicy, ::Kessel::Inventory::V1beta1::Resources::DeleteK8sPolicyRequest, ::Kessel::Inventory::V1beta1::Resources::DeleteK8sPolicyResponse
          end

          Stub = Service.rpc_stub_class
        end
      end
    end
  end
end
