# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kessel/inventory/v1beta1/resources/k8s_cluster_detail_nodes_inner.proto

require 'google/protobuf'

require 'buf/validate/validate_pb'
require 'kessel/inventory/v1beta1/resources/resource_label_pb'


descriptor_data = "\nGkessel/inventory/v1beta1/resources/k8s_cluster_detail_nodes_inner.proto\x12\"kessel.inventory.v1beta1.resources\x1a\x1b\x62uf/validate/validate.proto\x1a\x37kessel/inventory/v1beta1/resources/resource_label.proto\"\xd8\x01\n\x1aK8sClusterDetailNodesInner\x12\x1e\n\x04name\x18\x8b\xf5\xcd\x01 \x01(\tB\x07\xbaH\x04r\x02\x10\x01R\x04name\x12\x1b\n\x03\x63pu\x18\xa8\x83\x06 \x01(\tB\x07\xbaH\x04r\x02\x10\x01R\x03\x63pu\x12\"\n\x06memory\x18\x81\x86\xf5\x01 \x01(\tB\x07\xbaH\x04r\x02\x10\x01R\x06memory\x12Y\n\x06labels\x18\x83\xc0\xbe\x11 \x03(\x0b\x32\x31.kessel.inventory.v1beta1.resources.ResourceLabelB\x0b\xbaH\x08\x92\x01\x05\"\x03\xc8\x01\x01R\x06labelsB\xa7\x01\n2org.project_kessel.api.inventory.v1beta1.resourcesB\x1fK8sClusterDetailNodesInnerProtoP\x01ZNgithub.com/project-kessel/inventory-api/api/kessel/inventory/v1beta1/resourcesb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Kessel
  module Inventory
    module V1beta1
      module Resources
        K8sClusterDetailNodesInner = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kessel.inventory.v1beta1.resources.K8sClusterDetailNodesInner").msgclass
      end
    end
  end
end
