# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kessel/inventory/v1beta1/resources/metadata.proto

require 'google/protobuf'

require 'google/api/field_behavior_pb'
require 'google/protobuf/timestamp_pb'
require 'kessel/inventory/v1beta1/resources/resource_label_pb'


descriptor_data = "\n1kessel/inventory/v1beta1/resources/metadata.proto\x12\"kessel.inventory.v1beta1.resources\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x37kessel/inventory/v1beta1/resources/resource_label.proto\"\xa1\x03\n\x08Metadata\x12\x14\n\x02id\x18\x9b\x1a \x01(\tB\x03\xe0\x41\x03R\x02id\x12-\n\rresource_type\x18\xcc\xb9\x8f\xd3\x01 \x01(\tB\x03\xe0\x41\x03R\rresource_type\x12@\n\ncreated_at\x18\xc8\x1a \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x03\xe0\x41\x03R\ncreated_at\x12@\n\nupdated_at\x18\xc9\x1a \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x03\xe0\x41\x03R\nupdated_at\x12@\n\ndeleted_at\x18\xca\x1a \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x03\xe0\x41\x03R\ndeleted_at\x12\x17\n\x06org_id\x18\xac\x1b \x01(\tR\x06org_id\x12#\n\x0cworkspace_id\x18\xad\x1b \x01(\tR\x0cworkspace_id\x12L\n\x06labels\x18\x99\xe8\xd8\x01 \x03(\x0b\x32\x31.kessel.inventory.v1beta1.resources.ResourceLabelR\x06labelsB\x86\x01\n2org.project_kessel.api.inventory.v1beta1.resourcesP\x01ZNgithub.com/project-kessel/inventory-api/api/kessel/inventory/v1beta1/resourcesb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Kessel
  module Inventory
    module V1beta1
      module Resources
        Metadata = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kessel.inventory.v1beta1.resources.Metadata").msgclass
      end
    end
  end
end
