# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kessel/inventory/v1beta1/resources/reporter_data.proto

require 'google/protobuf'

require 'google/api/field_behavior_pb'
require 'buf/validate/validate_pb'


descriptor_data = "\n6kessel/inventory/v1beta1/resources/reporter_data.proto\x12\"kessel.inventory.v1beta1.resources\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1b\x62uf/validate/validate.proto\"\xe7\x03\n\x0cReporterData\x12s\n\rreporter_type\x18\xd8\x8f\x99u \x01(\x0e\x32=.kessel.inventory.v1beta1.resources.ReporterData.ReporterTypeB\x0b\xbaH\x08\x82\x01\x05\x10\x01\"\x01\x00R\rreporter_type\x12:\n\x14reporter_instance_id\x18\xb8\xd5\xfar \x01(\tB\x03\xe0\x41\x03R\x14reporter_instance_id\x12%\n\x0c\x63onsole_href\x18\x94\xa2\xc6\x45 \x01(\tR\x0c\x63onsole_href\x12\x1e\n\x08\x61pi_href\x18\xb1\xfc\x91\xcd\x01 \x01(\tR\x08\x61pi_href\x12\x39\n\x11local_resource_id\x18\xbd\xb8\xd9\xf2\x01 \x01(\tB\x07\xbaH\x04r\x02\x10\x01R\x11local_resource_id\x12.\n\x10reporter_version\x18\xfa\xee\xc8\x80\x01 \x01(\tR\x10reporter_version\"t\n\x0cReporterType\x12\x1d\n\x19REPORTER_TYPE_UNSPECIFIED\x10\x00\x12\x17\n\x13REPORTER_TYPE_OTHER\x10\x01\x12\x07\n\x03\x41\x43M\x10\x02\x12\x07\n\x03HBI\x10\x03\x12\x07\n\x03OCM\x10\x04\x12\x11\n\rNOTIFICATIONS\x10\x05\x42\x86\x01\n2org.project_kessel.api.inventory.v1beta1.resourcesP\x01ZNgithub.com/project-kessel/inventory-api/api/kessel/inventory/v1beta1/resourcesb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Kessel
  module Inventory
    module V1beta1
      module Resources
        ReporterData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kessel.inventory.v1beta1.resources.ReporterData").msgclass
        ReporterData::ReporterType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kessel.inventory.v1beta1.resources.ReporterData.ReporterType").enummodule
      end
    end
  end
end
