# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kessel/inventory/v1beta1/resources/resource_label.proto

require 'google/protobuf'

require 'buf/validate/validate_pb'


descriptor_data = "\n7kessel/inventory/v1beta1/resources/resource_label.proto\x12\"kessel.inventory.v1beta1.resources\x1a\x1b\x62uf/validate/validate.proto\"N\n\rResourceLabel\x12\x1b\n\x03key\x18\xdf\xbc\x06 \x01(\tB\x07\xbaH\x04r\x02\x10\x01R\x03key\x12 \n\x05value\x18\xf1\xa2\xb2\x35 \x01(\tB\x07\xbaH\x04r\x02\x10\x01R\x05valueB\x86\x01\n2org.project_kessel.api.inventory.v1beta1.resourcesP\x01ZNgithub.com/project-kessel/inventory-api/api/kessel/inventory/v1beta1/resourcesb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Kessel
  module Inventory
    module V1beta1
      module Resources
        ResourceLabel = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kessel.inventory.v1beta1.resources.ResourceLabel").msgclass
      end
    end
  end
end
